import type { Task } from "@/types/tasks.types";

/** Static demo tasks shown as a watermark when real data is empty */
export const MOCK_TASKS: Task[] = [
  {
    id: "mock-1",
    workspaceId: "mock",
    title: "Follow up with Rahul about course enrollment",
    description: "He asked for a call back before end of week to discuss batch options.",
    assignedToId: "mock-member-1",
    assignedById: "mock-member-2",
    referredByMemberId: null,
    referredByName: null,
    dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    priority: "URGENT",
    status: "IN_PROGRESS",
    completionNote: null,
    completedAt: null,
    declineNote: null,
    linkedEntityType: "student",
    linkedEntityId: null,
    dueSoonNotifiedAt: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isOverdue: false,
    assignedTo: { user: { name: "Priya Sharma" } },
    assignedBy: { user: { name: "Avishek Dev" } },
    taskTypeId: null,
  },
  {
    id: "mock-2",
    workspaceId: "mock",
    title: "Send batch schedule to Group A students",
    description: "Upload revised timetable PDF and notify all enrolled students.",
    assignedToId: "mock-member-1",
    assignedById: "mock-member-1",
    referredByMemberId: null,
    referredByName: null,
    dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    priority: "NORMAL",
    status: "ACCEPTED",
    completionNote: null,
    completedAt: null,
    declineNote: null,
    linkedEntityType: "group",
    linkedEntityId: null,
    dueSoonNotifiedAt: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isOverdue: false,
    assignedTo: { user: { name: "Priya Sharma" } },
    assignedBy: { user: { name: "Priya Sharma" } },
    taskTypeId: null,
  },
  {
    id: "mock-3",
    workspaceId: "mock",
    title: "Call list review — October batch",
    description: "Go through pending call list items and mark done or reschedule.",
    assignedToId: "mock-member-3",
    assignedById: "mock-member-2",
    referredByMemberId: null,
    referredByName: null,
    dueDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    priority: "URGENT",
    status: "ACCEPTED",
    completionNote: null,
    completedAt: null,
    declineNote: null,
    linkedEntityType: "call_list",
    linkedEntityId: null,
    dueSoonNotifiedAt: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isOverdue: true,
    assignedTo: { user: { name: "Tanvir Ahmed" } },
    assignedBy: { user: { name: "Avishek Dev" } },
    taskTypeId: null,
  },
  {
    id: "mock-4",
    workspaceId: "mock",
    title: "Update form for new student intake",
    description: "Add extra fields for guardian contact and previous institution.",
    assignedToId: "mock-member-2",
    assignedById: "mock-member-2",
    referredByMemberId: null,
    referredByName: null,
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    priority: "NORMAL",
    status: "AWAITING_ACCEPTANCE",
    completionNote: null,
    completedAt: null,
    declineNote: null,
    linkedEntityType: "form",
    linkedEntityId: null,
    dueSoonNotifiedAt: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isOverdue: false,
    assignedTo: { user: { name: "Avishek Dev" } },
    assignedBy: { user: { name: "Avishek Dev" } },
    taskTypeId: null,
  },
  {
    id: "mock-5",
    workspaceId: "mock",
    title: "Prepare monthly performance report",
    description: "Compile call stats, enrollment numbers, and follow-up completion rates.",
    assignedToId: "mock-member-3",
    assignedById: "mock-member-2",
    referredByMemberId: null,
    referredByName: null,
    dueDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    priority: "NORMAL",
    status: "DONE",
    completionNote: "Report sent to admin.",
    completedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    declineNote: null,
    linkedEntityType: null,
    linkedEntityId: null,
    dueSoonNotifiedAt: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isOverdue: false,
    assignedTo: { user: { name: "Tanvir Ahmed" } },
    assignedBy: { user: { name: "Avishek Dev" } },
    taskTypeId: null,
  },
];

export const MOCK_KPI = {
  totalActive: 3,
  completed: 12,
  overdue: 2,
  dueToday: 1,
};
